# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage', '~> 4.1'
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'Charts'
  pod 'Toast-Swift', '~> 5.0.0'
  pod "SwiftSpinner"
  pod "PullToRefreshKit"
end
